// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ66QyxtGXID-r1yg5BKGJOOiD4hIznSU',
    appId: '1:415550657895:web:ae1460a97b4a2442990bc2',
    messagingSenderId: '415550657895',
    projectId: 'fluttereaxm',
    authDomain: 'fluttereaxm.firebaseapp.com',
    storageBucket: 'fluttereaxm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo-pdsAld3auouihwRwVTolOJABXMXSPI',
    appId: '1:415550657895:android:f38cf37b34c4ad7d990bc2',
    messagingSenderId: '415550657895',
    projectId: 'fluttereaxm',
    storageBucket: 'fluttereaxm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUdZwScBAaV8zukl5oZp_T3yTBrxtTnFM',
    appId: '1:415550657895:ios:a79c905c42cf3875990bc2',
    messagingSenderId: '415550657895',
    projectId: 'fluttereaxm',
    storageBucket: 'fluttereaxm.appspot.com',
    iosBundleId: 'com.example.finalEaxmUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUdZwScBAaV8zukl5oZp_T3yTBrxtTnFM',
    appId: '1:415550657895:ios:a79c905c42cf3875990bc2',
    messagingSenderId: '415550657895',
    projectId: 'fluttereaxm',
    storageBucket: 'fluttereaxm.appspot.com',
    iosBundleId: 'com.example.finalEaxmUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ66QyxtGXID-r1yg5BKGJOOiD4hIznSU',
    appId: '1:415550657895:web:c7b0926238dfcd21990bc2',
    messagingSenderId: '415550657895',
    projectId: 'fluttereaxm',
    authDomain: 'fluttereaxm.firebaseapp.com',
    storageBucket: 'fluttereaxm.appspot.com',
  );
}
